user:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  avatar_width: 300
  avatar_heigh: 400
  remember_me:
    check: "1"
  avatar: 150
  avt_friend: 80
documents:
  file: ".pdf"
category:
  maximum_style: 20
