user:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  avatar_width: 300
  avatar_heigh: 400
  remember_me:
    check: "1"
  avatar: 150
  avt_friend: 80
  default_buy: 1
documents:
  file: ".pdf"
  illegal: 5
category:
  maximum_style: 30
comments:
  per_page: 8
  minimum_content: 10
mailer:
  default: "from@example.com"
history_downloads:
  down_times: 1
  max_down_free: 3
  cost_per_down: 10
